### ISSUE TITLE
working example

### ISSUE THREAD

**Issue by samarmir** [olivier-voutat/BlackStar.Localization#1]
Just downloaded the code, 
I find it difficult to understand and get to work. 
Would you kindly make a working (asp.net mvc core) example on how to use this.

**Comment by olivier-voutat** [comment]
Did u read the page indicated in the Readme file? https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization

**Comment by olivier-voutat** [comment]
If you make it work as it is described, you're just a step away from using my code to extend.
