### ISSUE TITLE
How dose the database table look like ?

### ISSUE THREAD

**Issue by LucaGabi** [olivier-voutat/BlackStar.Localization#2]
SELECT CultureName, ResourceKey, {_dbArgs["Column"]} FROM {_dbArgs["Table"]} WHERE Path LIKE @path", con))

What is Path ? 

Thanks.

**Comment by olivier-voutat** [comment]
line 124: cmd.Parameters.AddWithValue("@path", Common.Extract(_baseName));

_baseName is the full path to your view. Ex: "CustomerCenter.WebAppViews.Controls._CtrlLogin"

The Extract method gives you the two level path to your view. Ex: "Controls._CtrlLogin"

Each translation is related not only to a resourcekey but to a view or a controller.
