### ISSUE TITLE
Is there a way to reload the data if changed ?

### ISSUE THREAD

**Issue by LucaGabi** [olivier-voutat/BlackStar.Localization#3]
If I have an admin area and I have the ability to add roles how to translate those ?

**Comment by olivier-voutat** [comment]
CustomStringLocalizerFactoryCustomStringLocalizerFactory.cs

Line 90
        public void ClearCache()
        {
            _localizerCache.Clear();
        }

Call example
        public IActionResult ClearLangCache()
        {
            var localizerFactory = _service.GetService<IStringLocalizerFactory>() as CustomStringLocalizerFactory;
            localizerFactory.ClearCache();
            return View();
        }
