### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by LucaGabi** [olivier-voutat/BlackStar.Localization#4]
It works great.

I have one question: how is the IStringLocalizerFactory called how to add more types ?

I want to have localized data models, so that the value of a field is read from db by culture.

```
//seen in web UI editor
[Localized("Friendly name group")]
public class MyClass
{
    [LocalizedKey]
    public string MyProperty { get; set; }
}
```

The value of the field is the key on which the translation is done for the current culture.

I hope you can help.
Thanks.

**Comment by olivier-voutat** [comment]
I think you mean

```
public class Identity
{
    #region Properties

    [Display(Name = "M100_100")]
    [Required(ErrorMessage = "M100_101")]
    public string Login { get; set; }

    [Display(Name = "M100_102")]
    [Required(ErrorMessage = "M100_103")]
    public string Password { get; set; }

    #endregion Properties
}
```

The path value will be "Models.Identity" and the resourcekey is what is specified as M100_100, M100_101, etc

As mentionned in my README file, it simply replaces what is already available through https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization
