### ISSUE TITLE
DisplayFor in controller

### ISSUE THREAD

**Issue by LucaGabi** [olivier-voutat/BlackStar.Localization#5]
How can I get the value returned by DisplayFor like in a view  while I am in the controller action ?

Thanks.

**Comment by olivier-voutat** [comment]
I believe you cannot and even if you could, by experience, I would advise you to don't do it. Shared resources exists but should be used less than possible.  Shared resources can be use in views and controllers.

**Comment by olivier-voutat** [comment]
humm, in fact I think I was a little bit lazy on this one. I still advise you to use separated texts but...

I think there is a way to reuse a class DisplayFor text in the controller. In the example bellow `Resources.Shared` is a completely empty class used for shared resources.

```
        private readonly IHtmlLocalizer<Resources.Shared> _sharedLocalizer;

        public PagesController(IOptions<AppSettings> appSettings, IHtmlLocalizer<Resources.Shared> sharedLocalizer)
        {
            _appSettings = appSettings.Value;
            _sharedLocalizer = sharedLocalizer;
        }

        public IActionResult TestPage()
        {
            ViewData["shareTest"] = _sharedLocalizer["S999"];
        }
```
If it works for an empty class for shared resources, why not by a "real" class ;)
